name: Label
 
on: push
 
jobs:
  print-label:
    runs-on: ubuntu-latest
    steps:
      - name: Print build label
        run: echo "${{ format('build-{0}-{1}', github.run_number, github.ref_name) }}"
